[2019-04-21 07:36:10.0158], WARN , org.springframework.context.support.AbstractApplicationContext main - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' defined in class path resource [applicationContext-dao-test.xml]: Cannot resolve reference to bean 'classDataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classDataSource' defined in class path resource [applicationContext-dao-test.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
[2019-04-21 07:36:10.0162], ERROR, org.springframework.test.context.TestContextManager main - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@6c4980d3] to prepare test instance [com.smile.clz.api.core.service.impl.FewTestNgAdvancedFeatures1@6e75aa0d]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' defined in class path resource [applicationContext-dao-test.xml]: Cannot resolve reference to bean 'classDataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classDataSource' defined in class path resource [applicationContext-dao-test.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1531)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:108)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:251)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 28 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classDataSource' defined in class path resource [applicationContext-dao-test.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 46 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 55 more
Caused by: java.lang.NullPointerException
	at com.smile.clz.api.core.config.SmileDailyRollingFileAppender.cleanupAndRollOver(SmileDailyRollingFileAppender.java:202)
	at com.smile.clz.api.core.config.SmileDailyRollingFileAppender.subAppend(SmileDailyRollingFileAppender.java:170)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:209)
	at com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder.createMysqldResource(EmbeddedMysqlDatabaseBuilder.java:62)
	at com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder.build(EmbeddedMysqlDatabaseBuilder.java:116)
	at com.smile.clz.api.db.EmbeddedDataSourceConfig.dataSource(EmbeddedDataSourceConfig.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 56 more
[2019-04-21 07:36:10.0579], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - =============== Starting Embedded MySQL using these parameters ===============
[2019-04-21 07:36:10.0579], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - baseDatabaseDir : C:\Users\Hasitha\AppData\Local\Temp\
[2019-04-21 07:36:10.0581], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - databaseName : SVD_CLASS_DB_86215550185409
[2019-04-21 07:36:10.0582], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - host : localhost (hardcoded)
[2019-04-21 07:36:10.0583], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - port : 3608
[2019-04-21 07:36:10.0583], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - USERNAME : root (hardcode)
[2019-04-21 07:36:10.0584], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - PASSWORD : (no PASSWORD)
[2019-04-21 07:36:10.0584], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - =============================================================================
[2019-04-21 07:36:17.0880], INFO , com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - MySQL started successfully @ 1555812377878
[2019-04-21 07:36:17.0883], INFO , org.springframework.jdbc.datasource.DriverManagerDataSource main - Loaded JDBC driver: com.mysql.jdbc.Driver
[2019-04-21 07:36:17.0883], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - database url: jdbc:mysql://localhost:3608/SVD_CLASS_DB_86215550185409?createDatabaseIfNotExist=true
[2019-04-21 07:36:17.0900], DEBUG, org.springframework.jdbc.datasource.DriverManagerDataSource main - Creating new JDBC DriverManager Connection to [jdbc:mysql://localhost:3608/SVD_CLASS_DB_86215550185409?createDatabaseIfNotExist=true]
[2019-04-21 07:36:19.0065], DEBUG, org.springframework.jdbc.datasource.DriverManagerDataSource main - Creating new JDBC DriverManager Connection to [jdbc:mysql://localhost:3608/SVD_CLASS_DB_86215550185409?createDatabaseIfNotExist=true]
[2019-04-21 07:36:19.0114], DEBUG, org.springframework.jdbc.datasource.DriverManagerDataSource main - Creating new JDBC DriverManager Connection to [jdbc:mysql://localhost:3608/SVD_CLASS_DB_86215550185409?createDatabaseIfNotExist=true]
[2019-04-21 07:36:19.0217], DEBUG, org.springframework.jdbc.datasource.DriverManagerDataSource main - Creating new JDBC DriverManager Connection to [jdbc:mysql://localhost:3608/SVD_CLASS_DB_86215550185409?createDatabaseIfNotExist=true]
[2019-04-21 07:36:29.0961], WARN , org.springframework.context.support.AbstractApplicationContext main - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' defined in class path resource [applicationContext-dao-test.xml]: Cannot resolve reference to bean 'classDataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classDataSource' defined in class path resource [applicationContext-dao-test.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
[2019-04-21 07:36:29.0966], ERROR, org.springframework.test.context.TestContextManager main - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@6c4980d3] to prepare test instance [com.smile.clz.api.core.service.impl.FewTestNgAdvancedFeatures1@6e75aa0d]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' defined in class path resource [applicationContext-dao-test.xml]: Cannot resolve reference to bean 'classDataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classDataSource' defined in class path resource [applicationContext-dao-test.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1531)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:108)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:251)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 28 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classDataSource' defined in class path resource [applicationContext-dao-test.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 46 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 55 more
Caused by: java.lang.NullPointerException
	at com.smile.clz.api.core.config.SmileDailyRollingFileAppender.cleanupAndRollOver(SmileDailyRollingFileAppender.java:202)
	at com.smile.clz.api.core.config.SmileDailyRollingFileAppender.subAppend(SmileDailyRollingFileAppender.java:170)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:209)
	at com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder.createMysqldResource(EmbeddedMysqlDatabaseBuilder.java:62)
	at com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder.build(EmbeddedMysqlDatabaseBuilder.java:116)
	at com.smile.clz.api.db.EmbeddedDataSourceConfig.dataSource(EmbeddedDataSourceConfig.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 56 more
[2019-04-21 07:36:30.0238], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - =============== Starting Embedded MySQL using these parameters ===============
[2019-04-21 07:36:30.0239], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - baseDatabaseDir : C:\Users\Hasitha\AppData\Local\Temp\
[2019-04-21 07:36:30.0239], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - databaseName : SVD_CLASS_DB_86235209106121
[2019-04-21 07:36:30.0239], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - host : localhost (hardcoded)
[2019-04-21 07:36:30.0240], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - port : 4621
[2019-04-21 07:36:30.0240], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - USERNAME : root (hardcode)
[2019-04-21 07:36:30.0241], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - PASSWORD : (no PASSWORD)
[2019-04-21 07:36:30.0241], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - =============================================================================
[2019-04-21 07:36:37.0314], INFO , com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - MySQL started successfully @ 1555812397312
[2019-04-21 07:36:37.0316], INFO , org.springframework.jdbc.datasource.DriverManagerDataSource main - Loaded JDBC driver: com.mysql.jdbc.Driver
[2019-04-21 07:36:37.0316], DEBUG, com.smile.clz.api.db.EmbeddedMysqlDatabaseBuilder main - database url: jdbc:mysql://localhost:4621/SVD_CLASS_DB_86235209106121?createDatabaseIfNotExist=true
[2019-04-21 07:36:37.0322], DEBUG, org.springframework.jdbc.datasource.DriverManagerDataSource main - Creating new JDBC DriverManager Connection to [jdbc:mysql://localhost:4621/SVD_CLASS_DB_86235209106121?createDatabaseIfNotExist=true]
[2019-04-21 07:36:38.0473], DEBUG, org.springframework.jdbc.datasource.DriverManagerDataSource main - Creating new JDBC DriverManager Connection to [jdbc:mysql://localhost:4621/SVD_CLASS_DB_86235209106121?createDatabaseIfNotExist=true]
[2019-04-21 07:36:38.0525], DEBUG, org.springframework.jdbc.datasource.DriverManagerDataSource main - Creating new JDBC DriverManager Connection to [jdbc:mysql://localhost:4621/SVD_CLASS_DB_86235209106121?createDatabaseIfNotExist=true]
[2019-04-21 07:36:38.0631], DEBUG, org.springframework.jdbc.datasource.DriverManagerDataSource main - Creating new JDBC DriverManager Connection to [jdbc:mysql://localhost:4621/SVD_CLASS_DB_86235209106121?createDatabaseIfNotExist=true]
